/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Currency } from './currency';
import { Subaccount } from './subaccount';

export class Account {
    /**
    * The unique identifier for the user.
    */
    'userId'?: number;
    /**
    * The username of the user.
    */
    'username'?: string;
    /**
    * The email address of the user.
    */
    'userEmail'?: string;
    /**
    * Flag indicating if the user account is active.
    */
    'active'?: number;
    /**
    * Flag indicating if the user account is banned.
    */
    'banned'?: number;
    /**
    * The balance of the user\'s account.
    */
    'balance'?: string;
    /**
    * The phone number of the user.
    */
    'userPhone'?: string;
    /**
    * The email address to reply to.
    */
    'replyTo'?: string;
    /**
    * The delivery email address.
    */
    'deliveryTo'?: string | null;
    /**
    * The first name of the user.
    */
    'userFirstName'?: string;
    /**
    * The last name of the user.
    */
    'userLastName'?: string;
    /**
    * The account number.
    */
    'account'?: number;
    /**
    * The name of the account.
    */
    'accountName'?: string;
    /**
    * The billing email address of the account.
    */
    'accountBillingEmail'?: string;
    /**
    * The billing mobile number of the account.
    */
    'accountBillingMobile'?: string;
    /**
    * The country of the user.
    */
    'country'?: string;
    /**
    * The default country for SMS.
    */
    'defaultCountrySms'?: string;
    /**
    * Flag indicating if auto-recharge is enabled.
    */
    'autoRecharge'?: number;
    /**
    * The auto-recharge amount.
    */
    'autoRechargeAmount'?: string;
    /**
    * The low credit amount.
    */
    'lowCreditAmount'?: string;
    /**
    * Flag indicating if unicode SMS is enabled.
    */
    'settingUnicodeSms'?: number;
    /**
    * Flag indicating if email SMS subject is enabled.
    */
    'settingEmailSmsSubject'?: number;
    /**
    * Flag indicating if fixing sender ID is enabled.
    */
    'settingFixSenderId'?: number;
    /**
    * The SMS message character limit.
    */
    'settingSmsMessageCharLimit'?: number;
    /**
    * Flag indicating if old dashboard is enabled.
    */
    'oldDashboard'?: number;
    /**
    * The balance commission.
    */
    'balanceCommission'?: string;
    /**
    * The timezone of the user.
    */
    'timezone'?: string;
    /**
    * The pricing tier used to determine the cost per message.
    */
    'priceRate'?: number;
    'currency'?: Currency;
    'subaccount'?: Subaccount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "userEmail",
            "baseName": "user_email",
            "type": "string"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "number"
        },
        {
            "name": "banned",
            "baseName": "banned",
            "type": "number"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "string"
        },
        {
            "name": "userPhone",
            "baseName": "user_phone",
            "type": "string"
        },
        {
            "name": "replyTo",
            "baseName": "reply_to",
            "type": "string"
        },
        {
            "name": "deliveryTo",
            "baseName": "delivery_to",
            "type": "string"
        },
        {
            "name": "userFirstName",
            "baseName": "user_first_name",
            "type": "string"
        },
        {
            "name": "userLastName",
            "baseName": "user_last_name",
            "type": "string"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "number"
        },
        {
            "name": "accountName",
            "baseName": "account_name",
            "type": "string"
        },
        {
            "name": "accountBillingEmail",
            "baseName": "account_billing_email",
            "type": "string"
        },
        {
            "name": "accountBillingMobile",
            "baseName": "account_billing_mobile",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "defaultCountrySms",
            "baseName": "default_country_sms",
            "type": "string"
        },
        {
            "name": "autoRecharge",
            "baseName": "auto_recharge",
            "type": "number"
        },
        {
            "name": "autoRechargeAmount",
            "baseName": "auto_recharge_amount",
            "type": "string"
        },
        {
            "name": "lowCreditAmount",
            "baseName": "low_credit_amount",
            "type": "string"
        },
        {
            "name": "settingUnicodeSms",
            "baseName": "setting_unicode_sms",
            "type": "number"
        },
        {
            "name": "settingEmailSmsSubject",
            "baseName": "setting_email_sms_subject",
            "type": "number"
        },
        {
            "name": "settingFixSenderId",
            "baseName": "setting_fix_sender_id",
            "type": "number"
        },
        {
            "name": "settingSmsMessageCharLimit",
            "baseName": "setting_sms_message_char_limit",
            "type": "number"
        },
        {
            "name": "oldDashboard",
            "baseName": "old_dashboard",
            "type": "number"
        },
        {
            "name": "balanceCommission",
            "baseName": "balance_commission",
            "type": "string"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        },
        {
            "name": "priceRate",
            "baseName": "price_rate",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "_currency",
            "type": "Currency"
        },
        {
            "name": "subaccount",
            "baseName": "_subaccount",
            "type": "Subaccount"
        }    ];

    static getAttributeTypeMap() {
        return Account.attributeTypeMap;
    }
}

