/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Optional registration data for number compliance
*/
export class BuyNumberRequestRegistrationData {
    /**
    * Name of the business (2 - 100 characters)
    */
    'businessName': string;
    /**
    * Business address (5 - 150 characters)
    */
    'businessAddress': string;
    /**
    * Suburb/City (2 - 50 characters)
    */
    'suburb': string;
    /**
    * Postal code (2 - 20 characters)
    */
    'postcode': string;
    /**
    * State/Province (2 - 50 characters)
    */
    'state': string;
    /**
    * Contact person name (2 - 100 characters)
    */
    'contactName': string;
    /**
    * Contact phone number (valid local or international phone number)
    */
    'contactNumber': string;
    /**
    * Country code (ISO 3166-1 alpha-2)
    */
    'country': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "businessName",
            "baseName": "business_name",
            "type": "string"
        },
        {
            "name": "businessAddress",
            "baseName": "business_address",
            "type": "string"
        },
        {
            "name": "suburb",
            "baseName": "suburb",
            "type": "string"
        },
        {
            "name": "postcode",
            "baseName": "postcode",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "contactName",
            "baseName": "contact_name",
            "type": "string"
        },
        {
            "name": "contactNumber",
            "baseName": "contact_number",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BuyNumberRequestRegistrationData.attributeTypeMap;
    }
}

