/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Contact {
    /**
    * The unique identifier for the contact.
    */
    'contactId'?: number;
    /**
    * The identifier of the list the contact belongs to.
    */
    'listId'?: number;
    /**
    * The phone number of the contact.
    */
    'phoneNumber'?: string;
    /**
    * The first name of the contact.
    */
    'firstName'?: string;
    /**
    * The last name of the contact.
    */
    'lastName'?: string;
    /**
    * Custom field 1.
    */
    'custom1'?: string;
    /**
    * Custom field 2.
    */
    'custom2'?: string;
    /**
    * Custom field 3.
    */
    'custom3'?: string;
    /**
    * Custom field 4.
    */
    'custom4'?: string;
    /**
    * The date when the contact was added. Returned as a plain string rather than a strict date-time since the API sometimes returns a raw Unix timestamp (e.g. \"1783997542\") instead of ISO 8601.
    */
    'dateAdded'?: string;
    /**
    * The date when the contact was last updated. Returned as a plain string rather than a strict date-time since the API sometimes returns a raw Unix timestamp (e.g. \"1783997542\") instead of ISO 8601.
    */
    'dateUpdated'?: string;
    /**
    * The fax number of the contact.
    */
    'faxNumber'?: string | null;
    /**
    * The organization name of the contact.
    */
    'organizationName'?: string | null;
    /**
    * The email address of the contact.
    */
    'email'?: string | null;
    /**
    * The address line 1 of the contact.
    */
    'addressLine1'?: string | null;
    /**
    * The address line 2 of the contact.
    */
    'addressLine2'?: string | null;
    /**
    * The address city of the contact.
    */
    'addressCity'?: string | null;
    /**
    * The address state of the contact.
    */
    'addressState'?: string | null;
    /**
    * The address postal code of the contact.
    */
    'addressPostalCode'?: string | null;
    /**
    * The address country of the contact.
    */
    'addressCountry'?: string | null;
    /**
    * The name of the list the contact belongs to.
    */
    'listName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contactId",
            "baseName": "contact_id",
            "type": "number"
        },
        {
            "name": "listId",
            "baseName": "list_id",
            "type": "number"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "custom1",
            "baseName": "custom_1",
            "type": "string"
        },
        {
            "name": "custom2",
            "baseName": "custom_2",
            "type": "string"
        },
        {
            "name": "custom3",
            "baseName": "custom_3",
            "type": "string"
        },
        {
            "name": "custom4",
            "baseName": "custom_4",
            "type": "string"
        },
        {
            "name": "dateAdded",
            "baseName": "date_added",
            "type": "string"
        },
        {
            "name": "dateUpdated",
            "baseName": "date_updated",
            "type": "string"
        },
        {
            "name": "faxNumber",
            "baseName": "fax_number",
            "type": "string"
        },
        {
            "name": "organizationName",
            "baseName": "organization_name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "addressLine1",
            "baseName": "address_line_1",
            "type": "string"
        },
        {
            "name": "addressLine2",
            "baseName": "address_line_2",
            "type": "string"
        },
        {
            "name": "addressCity",
            "baseName": "address_city",
            "type": "string"
        },
        {
            "name": "addressState",
            "baseName": "address_state",
            "type": "string"
        },
        {
            "name": "addressPostalCode",
            "baseName": "address_postal_code",
            "type": "string"
        },
        {
            "name": "addressCountry",
            "baseName": "address_country",
            "type": "string"
        },
        {
            "name": "listName",
            "baseName": "_list_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Contact.attributeTypeMap;
    }
}

