/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateTestInboundSmsRequest {
    /**
    * The webhook URL where the inbound SMS will be sent to.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>You can create a webhook URL in <em>Pipedream</em> to test receiving the inbound SMS. Follow the instructions <a href=\"https://help.clicksend.com/en/articles/43703-integration-guide-pipedream\" target=\"_blank\">here.</a></p> </div>  
    */
    'url': string;
    /**
    * Specifies the HTTP method used when the webhook sends a request to the URL. The available options are:  - **post** (Default): Sends the event data using an HTTP POST request.      - **get**: Sends the event data as query parameters in an HTTP GET request.      - **json**: Sends the event data using a custom JSON format (via a POST request).      This parameter is used to determine how the data will be transmitted, depending on your preferred method and how the receiving system is designed to process incoming requests.
    */
    'webhookType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateTestInboundSmsRequest.attributeTypeMap;
    }
}

