/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The parameters related to the message receipt.
*/
export class CreateTestSmsReceiptData {
    /**
    * The time you sent the test message. It is in <a target=\"_blank\" href=\"http://help.clicksend.com/what-is-a-unix-timestamp\">Unix format.</a>
    */
    'timestampSend'?: number;
    /**
    * The time you receive the test message receipt. It is in <a target=\"_blank\" href=\"http://help.clicksend.com/what-is-a-unix-timestamp\">Unix format.</a>
    */
    'timestamp'?: number;
    /**
    * The generated ID of the message. This ID is typically used as a reference for <a target=\"_blank\" href=\"https://www.clicksend.com/au/help/\">customer support</a> in case of any issues.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>This <em>message_id</em> is different from the ID that is generated when sending or receving an actual SMS. This ID is used for testing only.</p> </div>
    */
    'messageId'?: string;
    /**
    * The status code that is sent from the <a target=\"_blank\" href=\"https://en.wikipedia.org/wiki/SMS_gateway\">SMS gateway.</a> Visit <a target=\"_blank\" href=\"https://help.clicksend.com/article/8cc479qlbb-list-of-sms-gateway-error-codes\">this page</a> for more information.
    */
    'statusCode'?: number;
    /**
    * A message describing the _status_code_ of the operation. Visit <a target=\"_blank\" href=\"https://help.clicksend.com/article/8cc479qlbb-list-of-sms-gateway-error-codes\">this</a> page for more information.
    */
    'statusText'?: string;
    /**
    * The error code of the operation. Visit <a target=\"_blank\" href=\"https://help.clicksend.com/article/8cc479qlbb-list-of-sms-gateway-error-codes\">this page</a> for more information. If no error occurred, the value is **null**.
    */
    'errorCode'?: number | null;
    /**
    * A message describing the _error_code_ of the operation. Visit <a target=\"_blank\" href=\"https://help.clicksend.com/article/8cc479qlbb-list-of-sms-gateway-error-codes\">this page</a> for more information. If no error occurred, the value is **null**.
    */
    'errorText'?: string | null;
    /**
    * A note that was sent from the request.  <div class=\"warning-box\">   <h4><i class=\"fas fa-exclamation-triangle\"></i> Warning:</h4>   <p>This parameter is deprecated and will return <strong>null.</strong></p> </div>
    */
    'customString'?: string | null;
    /**
    * The sub-account of the user. A user can have multiple sub-accounts.
    */
    'subaccountId'?: number;
    /**
    * The type of message (e.g. SMS, MMS, etc).
    */
    'messageType'?: string;
    /**
    * The numbers that the recipient pressed on their keypad during the call. A **null** value is returned if the recipient didn\'t provide any input.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>This parameter is only relevant to <a href=\"/messaging/voice-messaging/\"><strong>Voice Messaging</strong></a> receipts.</p> </div>
    */
    'digits'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestampSend",
            "baseName": "timestamp_send",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "status_code",
            "type": "number"
        },
        {
            "name": "statusText",
            "baseName": "status_text",
            "type": "string"
        },
        {
            "name": "errorCode",
            "baseName": "error_code",
            "type": "number"
        },
        {
            "name": "errorText",
            "baseName": "error_text",
            "type": "string"
        },
        {
            "name": "customString",
            "baseName": "custom_string",
            "type": "string"
        },
        {
            "name": "subaccountId",
            "baseName": "subaccount_id",
            "type": "number"
        },
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "string"
        },
        {
            "name": "digits",
            "baseName": "digits",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateTestSmsReceiptData.attributeTypeMap;
    }
}

