/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The parameters related to currency.
*/
export class Currency {
    /**
    * The currency used for the sender in three-letter format (e.g. USD, EUR, AUD, NZD, etc).
    */
    'currencyNameShort'?: string;
    /**
    * The symbol used to indicate the currency of the sender (e.g. $ , €, etc).
    */
    'currencyPrefixD'?: string;
    /**
    * The currency basic unit (e.g. cents).
    */
    'currencyPrefixC'?: string;
    /**
    * The full name of the currency.
    */
    'currencyNameLong'?: string;
    /**
    * The minimum amount that can be used to recharge the account, in this currency.
    */
    'minRechargeAmount'?: string;
    /**
    * The maximum amount that can be used to recharge the account, in this currency.
    */
    'maxRechargeAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currencyNameShort",
            "baseName": "currency_name_short",
            "type": "string"
        },
        {
            "name": "currencyPrefixD",
            "baseName": "currency_prefix_d",
            "type": "string"
        },
        {
            "name": "currencyPrefixC",
            "baseName": "currency_prefix_c",
            "type": "string"
        },
        {
            "name": "currencyNameLong",
            "baseName": "currency_name_long",
            "type": "string"
        },
        {
            "name": "minRechargeAmount",
            "baseName": "min_recharge_amount",
            "type": "string"
        },
        {
            "name": "maxRechargeAmount",
            "baseName": "max_recharge_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Currency.attributeTypeMap;
    }
}

