/**
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* All dates before specified timestamp.
*/
export class DateBefore {
    /**
    * An optional timestamp - mark all as read before this timestamp. If not given, all messages will be marked as read.
    */
    'dateBefore'?: number;

    static discriminator: string | undefined = "classType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateBefore",
            "baseName": "date_before",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DateBefore.attributeTypeMap;
    }
}

