/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DefaultSenderDefaultSenderStrategiesInner {
    /**
    * Type of the sender.
    */
    'senderType': DefaultSenderDefaultSenderStrategiesInner.SenderTypeEnum;
    /**
    * Identifier for the sender. Must be between 3-20 characters.
    */
    'senderId': string;
    /**
    * ISO 3166-1 alpha-2 formatted country code.
    */
    'senderCountryCode'?: string;
    /**
    * Priority level of the sender in the strategy. Must be a positive integer.
    */
    'priority': number;
    /**
    * Status of the sender in the strategy.
    */
    'status': DefaultSenderDefaultSenderStrategiesInner.StatusEnum;
    /**
    * Note providing additional context about the sender. Maximum length of 200 characters. Optional.
    */
    'note'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "senderType",
            "baseName": "sender_type",
            "type": "DefaultSenderDefaultSenderStrategiesInner.SenderTypeEnum"
        },
        {
            "name": "senderId",
            "baseName": "sender_id",
            "type": "string"
        },
        {
            "name": "senderCountryCode",
            "baseName": "sender_country_code",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DefaultSenderDefaultSenderStrategiesInner.StatusEnum"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DefaultSenderDefaultSenderStrategiesInner.attributeTypeMap;
    }
}

export namespace DefaultSenderDefaultSenderStrategiesInner {
    export enum SenderTypeEnum {
        AlphaTag = <any> 'alpha_tag',
        _10Dlc = <any> '10DLC',
        Tollfree = <any> 'tollfree',
        OwnNumber = <any> 'own_number',
        Shortcode = <any> 'shortcode',
        Longcode = <any> 'longcode',
        SharedLongcode = <any> 'shared_longcode'
    }
    export enum StatusEnum {
        Enabled = <any> 'ENABLED',
        Disabled = <any> 'DISABLED'
    }
}
