/**
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Email-to-SMS Allowed Address
*/
export class EmailSMSAddress {
    /**
    * Your email address
    */
    'emailAddress': string;
    /**
    * Your sender id
    */
    'from': string;
    /**
    * Your subaccount id
    */
    'subaccountId'?: string;

    static discriminator: string | undefined = "classType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "subaccountId",
            "baseName": "subaccount_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EmailSMSAddress.attributeTypeMap;
    }
}

