/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Mms {
    /**
    * The ID of the list (if applicable).
    */
    'listId'?: string | null;
    /**
    * The ID of the contact.
    */
    'contactId'?: number;
    /**
    * The ID of the message.
    */
    'messageId'?: string;
    /**
    * The recipient of the message.
    */
    'to'?: string;
    /**
    * The subject of the message.
    */
    'subject'?: string;
    /**
    * The sender of the message.
    */
    'from'?: string;
    /**
    * The body of the message.
    */
    'body'?: string;
    /**
    * The country code.
    */
    'country'?: string;
    /**
    * Custom string associated with the message.
    */
    'customString'?: string;
    /**
    * The schedule time of the message.
    */
    'schedule'?: string;
    /**
    * The number of parts the message was split into.
    */
    'messageParts'?: number;
    /**
    * The price of the message.
    */
    'messagePrice'?: string;
    /**
    * The URL of the media file attached to the message.
    */
    'mediaFileUrl'?: string;
    /**
    * The status of the message.
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "listId",
            "baseName": "list_id",
            "type": "string"
        },
        {
            "name": "contactId",
            "baseName": "contact_id",
            "type": "number"
        },
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "customString",
            "baseName": "custom_string",
            "type": "string"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "string"
        },
        {
            "name": "messageParts",
            "baseName": "message_parts",
            "type": "number"
        },
        {
            "name": "messagePrice",
            "baseName": "message_price",
            "type": "string"
        },
        {
            "name": "mediaFileUrl",
            "baseName": "_media_file_url",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Mms.attributeTypeMap;
    }
}

