/**
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MmsMessage } from './mmsMessage';

/**
* Array of MmsMessage items
*/
export class MmsMessageCollection {
    /**
    * Media file you want to send
    */
    'mediaFile': string;
    /**
    * Array of MmsMessage models
    */
    'messages': Array<MmsMessage>;

    static discriminator: string | undefined = "classType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mediaFile",
            "baseName": "media_file",
            "type": "string"
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<MmsMessage>"
        }    ];

    static getAttributeTypeMap() {
        return MmsMessageCollection.attributeTypeMap;
    }
}

