/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OwnNumber {
    /**
    * The unique identifier for the record.
    */
    'id'?: string;
    /**
    * The unique identifier for the account.
    */
    'accountId'?: string;
    /**
    * The unique identifier for the workspace.
    */
    'workspaceId'?: string;
    /**
    * The unique identifier for the user.
    */
    'userId'?: string;
    /**
    * The user\'s phone number.
    */
    'phoneNumber'?: string;
    /**
    * The country code of the phone number.
    */
    'country'?: string;
    /**
    * A label for the phone number.
    */
    'label'?: string;
    /**
    * The status of the phone number.
    */
    'status'?: string;
    /**
    * The timestamp when the phone number was verified.
    */
    'verifiedTimestamp'?: Date;
    /**
    * The timestamp when the user was last notified about this number, if applicable.
    */
    'notifiedTimestamp'?: string | null;
    /**
    * Indicates whether the phone number verification is nearing its expiration date: - **true:** The verification was completed more than 11 months ago and will expire soon. You should re-verify your phone number to maintain uninterrupted service. - **false:** The verification is still valid and not approaching expiration.
    */
    'isNearingExpiration'?: boolean;
    /**
    * The timestamp when the record was created.
    */
    'createdTimestamp'?: Date;
    /**
    * The timestamp when the record was last updated.
    */
    'updatedTimestamp'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "workspaceId",
            "baseName": "workspace_id",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "verifiedTimestamp",
            "baseName": "verified_timestamp",
            "type": "Date"
        },
        {
            "name": "notifiedTimestamp",
            "baseName": "notified_timestamp",
            "type": "string"
        },
        {
            "name": "isNearingExpiration",
            "baseName": "is_nearing_expiration",
            "type": "boolean"
        },
        {
            "name": "createdTimestamp",
            "baseName": "created_timestamp",
            "type": "Date"
        },
        {
            "name": "updatedTimestamp",
            "baseName": "updated_timestamp",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return OwnNumber.attributeTypeMap;
    }
}

