/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResellerAccount {
    /**
    * The user\'s ID
    */
    'userId'?: number;
    /**
    * The username
    */
    'username'?: string;
    /**
    * The user\'s email
    */
    'userEmail'?: string;
    /**
    * Indicates if the user is active
    */
    'active'?: number;
    /**
    * Indicates if the user is banned
    */
    'banned'?: number;
    /**
    * The user\'s balance
    */
    'balance'?: string;
    /**
    * The user\'s phone number
    */
    'userPhone'?: string;
    /**
    * The reply-to email address
    */
    'replyTo'?: string;
    /**
    * The delivery-to email address
    */
    'deliveryTo'?: string | null;
    /**
    * The user\'s first name
    */
    'userFirstName'?: string;
    /**
    * The user\'s last name
    */
    'userLastName'?: string;
    /**
    * The user\'s account number
    */
    'account'?: number;
    /**
    * The name of the user\'s account
    */
    'accountName'?: string;
    /**
    * The account billing email
    */
    'accountBillingEmail'?: string;
    /**
    * The account billing mobile number
    */
    'accountBillingMobile'?: string;
    /**
    * The user\'s country
    */
    'country'?: string;
    /**
    * The default country for SMS
    */
    'defaultCountrySms'?: string;
    /**
    * Indicates if auto-recharge is enabled
    */
    'autoRecharge'?: number;
    /**
    * The auto-recharge amount
    */
    'autoRechargeAmount'?: string;
    /**
    * The low credit amount
    */
    'lowCreditAmount'?: string;
    /**
    * Setting for Unicode SMS
    */
    'settingUnicodeSms'?: number;
    /**
    * Setting for email SMS subject
    */
    'settingEmailSmsSubject'?: number;
    /**
    * Setting for fixed sender ID
    */
    'settingFixSenderId'?: number;
    /**
    * Setting for SMS message character limit
    */
    'settingSmsMessageCharLimit'?: number;
    /**
    * Indicates if the user is using the old dashboard
    */
    'oldDashboard'?: number;
    /**
    * The balance commission
    */
    'balanceCommission'?: string;
    /**
    * The user\'s timezone
    */
    'timezone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "userEmail",
            "baseName": "user_email",
            "type": "string"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "number"
        },
        {
            "name": "banned",
            "baseName": "banned",
            "type": "number"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "string"
        },
        {
            "name": "userPhone",
            "baseName": "user_phone",
            "type": "string"
        },
        {
            "name": "replyTo",
            "baseName": "reply_to",
            "type": "string"
        },
        {
            "name": "deliveryTo",
            "baseName": "delivery_to",
            "type": "string"
        },
        {
            "name": "userFirstName",
            "baseName": "user_first_name",
            "type": "string"
        },
        {
            "name": "userLastName",
            "baseName": "user_last_name",
            "type": "string"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "number"
        },
        {
            "name": "accountName",
            "baseName": "account_name",
            "type": "string"
        },
        {
            "name": "accountBillingEmail",
            "baseName": "account_billing_email",
            "type": "string"
        },
        {
            "name": "accountBillingMobile",
            "baseName": "account_billing_mobile",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "defaultCountrySms",
            "baseName": "default_country_sms",
            "type": "string"
        },
        {
            "name": "autoRecharge",
            "baseName": "auto_recharge",
            "type": "number"
        },
        {
            "name": "autoRechargeAmount",
            "baseName": "auto_recharge_amount",
            "type": "string"
        },
        {
            "name": "lowCreditAmount",
            "baseName": "low_credit_amount",
            "type": "string"
        },
        {
            "name": "settingUnicodeSms",
            "baseName": "setting_unicode_sms",
            "type": "number"
        },
        {
            "name": "settingEmailSmsSubject",
            "baseName": "setting_email_sms_subject",
            "type": "number"
        },
        {
            "name": "settingFixSenderId",
            "baseName": "setting_fix_sender_id",
            "type": "number"
        },
        {
            "name": "settingSmsMessageCharLimit",
            "baseName": "setting_sms_message_char_limit",
            "type": "number"
        },
        {
            "name": "oldDashboard",
            "baseName": "old_dashboard",
            "type": "number"
        },
        {
            "name": "balanceCommission",
            "baseName": "balance_commission",
            "type": "string"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResellerAccount.attributeTypeMap;
    }
}

