/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SendersInner {
    /**
    * Recipient ISO country code
    */
    'recipientCountryCode': string;
    /**
    * The sender ID must be either an alpha tag or a phone number. It is a required field unless the sender type is a `shared_longcode`.   If the sender ID is an **alpha tag**, it must be between 3 and 11 characters long and contains only letters, numbers, and pluses. 
    */
    'senderId'?: string;
    /**
    * The type of sender ID, it only supports `shared_longcode` at the moment.
    */
    'senderType'?: SendersInner.SenderTypeEnum;
    /**
    * The ISO 3166-1 alpha-2 country code that identifies the country associated with the sender’s number in a shared pool. This is affected only when `sender_type` is set to `shared_longcode` to determine the appropriate number based on the sender’s geographic location. If this field is not provided or left empty, it will default to the recipient\'s country code. 
    */
    'senderCountryCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recipientCountryCode",
            "baseName": "recipient_country_code",
            "type": "string"
        },
        {
            "name": "senderId",
            "baseName": "sender_id",
            "type": "string"
        },
        {
            "name": "senderType",
            "baseName": "sender_type",
            "type": "SendersInner.SenderTypeEnum"
        },
        {
            "name": "senderCountryCode",
            "baseName": "sender_country_code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SendersInner.attributeTypeMap;
    }
}

export namespace SendersInner {
    export enum SenderTypeEnum {
        SharedLongcode = <any> 'shared_longcode'
    }
}
