/**
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Campaign Model for SMS
*/
export class SmsCampaign {
    /**
    * Your list id.
    */
    'listId': number;
    /**
    * Your campaign name.
    */
    'name': string;
    /**
    * Your campaign message.
    */
    'body': string;
    /**
    * Your sender id - more info: https://help.clicksend.com/en/collections/57584-numbers-sender-ids.
    */
    'from'?: string;
    /**
    * Your schedule timestamp.
    */
    'schedule'?: number = 0;
    /**
    * url to be shortened add http://smsg.io/xxxxx` to the body as a placeholder.
    */
    'urlToShorten'?: string;

    static discriminator: string | undefined = "classType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "listId",
            "baseName": "list_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "number"
        },
        {
            "name": "urlToShorten",
            "baseName": "url_to_shorten",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SmsCampaign.attributeTypeMap;
    }
}

