/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SmsInboundRule {
    /**
    * The ID of the inbound rule.
    */
    'inboundRuleId'?: number;
    /**
    * The number to be used in the inbound rule.
    */
    'dedicatedNumber'?: string;
    /**
    * The name of the inbound rule.
    */
    'ruleName'?: string;
    /**
    * The type of message search to be used in the inbound rule.
    */
    'messageSearchType'?: number;
    /**
    * The message search term to be used in the inbound rule.
    */
    'messageSearchTerm'?: string;
    /**
    * The action to be taken in the inbound rule.
    */
    'action'?: string;
    /**
    * The action address to be used in the inbound rule.
    */
    'actionAddress'?: string;
    /**
    * The body of the inbound rule.
    */
    'body'?: string | null;
    /**
    * The status of the inbound rule.
    */
    'enabled'?: number;
    /**
    * The format used when calling the webhook (e.g. post, json).
    */
    'webhookType'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inboundRuleId",
            "baseName": "inbound_rule_id",
            "type": "number"
        },
        {
            "name": "dedicatedNumber",
            "baseName": "dedicated_number",
            "type": "string"
        },
        {
            "name": "ruleName",
            "baseName": "rule_name",
            "type": "string"
        },
        {
            "name": "messageSearchType",
            "baseName": "message_search_type",
            "type": "number"
        },
        {
            "name": "messageSearchTerm",
            "baseName": "message_search_term",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "actionAddress",
            "baseName": "action_address",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "number"
        },
        {
            "name": "webhookType",
            "baseName": "webhook_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SmsInboundRule.attributeTypeMap;
    }
}

