/**
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* SmsMessage model
*/
export class SmsMessage {
    /**
    * Your sender id - more info: https://help.clicksend.com/en/collections/57584-numbers-sender-ids.
    */
    'from'?: string;
    /**
    * Your message.
    */
    'body': string;
    /**
    * Recipient phone number in E.164 format.
    */
    'to'?: string;
    /**
    * Your method of sending e.g. \'wordpress\', \'php\', \'c#\'.
    */
    'source'?: string = 'sdk';
    /**
    * Leave blank for immediate delivery. Your schedule time in unix format https://help.clicksend.com/en/articles/44235-what-is-a-unix-timestamp
    */
    'schedule'?: number = 0;
    /**
    * Your reference. Will be passed back with all replies and delivery reports.
    */
    'customString'?: string;
    /**
    * Your list ID if sending to a whole list. Can be used instead of \'to\'.
    */
    'listId'?: number;
    /**
    * Recipient country.
    */
    'country'?: string;
    /**
    * An email address where the reply should be emailed to. If omitted, the reply will be emailed back to the user who sent the outgoing SMS.
    */
    'fromEmail'?: string;

    static discriminator: string | undefined = "classType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "number"
        },
        {
            "name": "customString",
            "baseName": "custom_string",
            "type": "string"
        },
        {
            "name": "listId",
            "baseName": "list_id",
            "type": "number"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "fromEmail",
            "baseName": "from_email",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SmsMessage.attributeTypeMap;
    }
}

