/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Subaccount {
    /**
    * The unique identifier for the subaccount.
    */
    'subaccountId'?: number;
    /**
    * The API username of the subaccount.
    */
    'apiUsername'?: string;
    /**
    * The email address of the subaccount.
    */
    'email'?: string;
    /**
    * The phone number of the subaccount.
    */
    'phoneNumber'?: string;
    /**
    * The first name of the subaccount.
    */
    'firstName'?: string;
    /**
    * The last name of the subaccount.
    */
    'lastName'?: string;
    /**
    * The API key of the subaccount.
    */
    'apiKey'?: string;
    /**
    * Flag indicating if the subaccount has access to users.
    */
    'accessUsers'?: number;
    /**
    * Flag indicating if the subaccount has access to billing.
    */
    'accessBilling'?: number;
    /**
    * Flag indicating if the subaccount has access to reporting.
    */
    'accessReporting'?: number;
    /**
    * Flag indicating if the subaccount has access to contacts.
    */
    'accessContacts'?: number;
    /**
    * Flag indicating if the subaccount has access to settings.
    */
    'accessSettings'?: number;
    /**
    * Flag indicating if the subaccount has access to SMS.
    */
    'accessSms'?: number;
    /**
    * Flag indicating if the subaccount has access to email.
    */
    'accessEmail'?: number;
    /**
    * Flag indicating if the subaccount has access to voice services.
    */
    'accessVoice'?: number;
    /**
    * Flag indicating if the subaccount has access to fax services.
    */
    'accessFax'?: number;
    /**
    * Flag indicating if the subaccount has access to post services.
    */
    'accessPost'?: number;
    /**
    * Flag indicating if the subaccount has access to reseller services.
    */
    'accessReseller'?: number;
    /**
    * Flag indicating if the subaccount has access to MMS services.
    */
    'accessMms'?: number;
    /**
    * Flag indicating if the subaccount can share campaigns.
    */
    'shareCampaigns'?: number;
    /**
    * Additional notes for the subaccount.
    */
    'notes'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subaccountId",
            "baseName": "subaccount_id",
            "type": "number"
        },
        {
            "name": "apiUsername",
            "baseName": "api_username",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string"
        },
        {
            "name": "apiKey",
            "baseName": "api_key",
            "type": "string"
        },
        {
            "name": "accessUsers",
            "baseName": "access_users",
            "type": "number"
        },
        {
            "name": "accessBilling",
            "baseName": "access_billing",
            "type": "number"
        },
        {
            "name": "accessReporting",
            "baseName": "access_reporting",
            "type": "number"
        },
        {
            "name": "accessContacts",
            "baseName": "access_contacts",
            "type": "number"
        },
        {
            "name": "accessSettings",
            "baseName": "access_settings",
            "type": "number"
        },
        {
            "name": "accessSms",
            "baseName": "access_sms",
            "type": "number"
        },
        {
            "name": "accessEmail",
            "baseName": "access_email",
            "type": "number"
        },
        {
            "name": "accessVoice",
            "baseName": "access_voice",
            "type": "number"
        },
        {
            "name": "accessFax",
            "baseName": "access_fax",
            "type": "number"
        },
        {
            "name": "accessPost",
            "baseName": "access_post",
            "type": "number"
        },
        {
            "name": "accessReseller",
            "baseName": "access_reseller",
            "type": "number"
        },
        {
            "name": "accessMms",
            "baseName": "access_mms",
            "type": "number"
        },
        {
            "name": "shareCampaigns",
            "baseName": "share_campaigns",
            "type": "number"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Subaccount.attributeTypeMap;
    }
}

