/**
 * SMS
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Attachment } from './attachment';
import { Currency } from './currency';
import { SendEmailRequestToInner } from './sendEmailRequestToInner';

export class TransactionalEmail {
    /**
    * The ID of the user.
    */
    'userId'?: number;
    /**
    * The ID of the subaccount.
    */
    'subaccountId'?: number;
    /**
    * The ID of the from email address.
    */
    'fromEmailAddressId'?: number;
    /**
    * The name of the sender.
    */
    'fromName'?: string;
    'to'?: Array<SendEmailRequestToInner>;
    'cc'?: Array<SendEmailRequestToInner>;
    'bcc'?: Array<SendEmailRequestToInner>;
    /**
    * The subject of the email.
    */
    'subject'?: string;
    /**
    * The HTML body of the email.
    */
    'body'?: string;
    /**
    * The plain text body of the email.
    */
    'bodyPlainText'?: string;
    /**
    * The timestamp indicating the scheduled time of the email.
    */
    'schedule'?: number;
    /**
    * The ID of the email message.
    */
    'messageId'?: string;
    /**
    * The status of the email.
    */
    'status'?: string;
    /**
    * The text description of the email status.
    */
    'statusText'?: string;
    /**
    * The count of soft bounces.
    */
    'softBounceCount'?: number;
    /**
    * The count of hard bounces.
    */
    'hardBounceCount'?: number;
    /**
    * The price of the email.
    */
    'price'?: string;
    /**
    * The timestamp indicating when the email was added.
    */
    'dateAdded'?: number;
    /**
    * A custom string.
    */
    'customString'?: string | null;
    'attachments'?: Array<Attachment>;
    'currency'?: Currency;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number"
        },
        {
            "name": "subaccountId",
            "baseName": "subaccount_id",
            "type": "number"
        },
        {
            "name": "fromEmailAddressId",
            "baseName": "from_email_address_id",
            "type": "number"
        },
        {
            "name": "fromName",
            "baseName": "from_name",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Array<SendEmailRequestToInner>"
        },
        {
            "name": "cc",
            "baseName": "cc",
            "type": "Array<SendEmailRequestToInner>"
        },
        {
            "name": "bcc",
            "baseName": "bcc",
            "type": "Array<SendEmailRequestToInner>"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "bodyPlainText",
            "baseName": "body_plain_text",
            "type": "string"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "number"
        },
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "statusText",
            "baseName": "status_text",
            "type": "string"
        },
        {
            "name": "softBounceCount",
            "baseName": "soft_bounce_count",
            "type": "number"
        },
        {
            "name": "hardBounceCount",
            "baseName": "hard_bounce_count",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "dateAdded",
            "baseName": "date_added",
            "type": "number"
        },
        {
            "name": "customString",
            "baseName": "custom_string",
            "type": "string"
        },
        {
            "name": "attachments",
            "baseName": "_attachments",
            "type": "Array<Attachment>"
        },
        {
            "name": "currency",
            "baseName": "_currency",
            "type": "Currency"
        }    ];

    static getAttributeTypeMap() {
        return TransactionalEmail.attributeTypeMap;
    }
}

