/**
 * ClickSend v3 API
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * The version of the OpenAPI document: 3.1
 * Contact: support@clicksend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* VoiceMessage fields: source, to, list_id, body, lang, voice, schedule, custom_string, country
*/
export class VoiceMessage {
    /**
    * Your phone number in E.164 format.
    */
    'to'?: string;
    /**
    * Biscuit uv3nlCOjRk croissant chocolate lollipop chocolate muffin.
    */
    'body': string;
    /**
    * Either \'female\' or \'male\'.
    */
    'voice': string;
    /**
    * Your reference. Will be passed back with all replies and delivery reports.
    */
    'customString': string;
    /**
    * The country of the recipient.
    */
    'country': string;
    /**
    * Your method of sending e.g. \'wordpress\', \'php\', \'c#\'.
    */
    'source'?: string = 'sdk';
    /**
    * Your list ID if sending to a whole list. Can be used instead of \'to\'.
    */
    'listId'?: number;
    /**
    * au (string, required) - See section on available languages.
    */
    'lang'?: string;
    /**
    * Leave blank for immediate delivery. Your schedule time in unix format https://help.clicksend.com/en/articles/44235-what-is-a-unix-timestamp
    */
    'schedule'?: number;
    /**
    * Whether you want to receive a keypress from the call recipient
    */
    'requireInput'?: number = 0;
    /**
    * Whether to attempt to detect an answering machine or voicemail service and leave a message
    */
    'machineDetection'?: number = 0;

    static discriminator: string | undefined = "classType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "string"
        },
        {
            "name": "customString",
            "baseName": "custom_string",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "listId",
            "baseName": "list_id",
            "type": "number"
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "string"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "number"
        },
        {
            "name": "requireInput",
            "baseName": "require_input",
            "type": "number"
        },
        {
            "name": "machineDetection",
            "baseName": "machine_detection",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return VoiceMessage.attributeTypeMap;
    }
}

